# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-04 23:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TpPythonApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoriaPadre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TpPythonApp.Categoria'),
        ),
    ]
