# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-10 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TpPythonApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=255)),
                ('codigo', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='pais',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TpPythonApp.Pais'),
        ),
    ]
