# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-07 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TpPythonApp', '0004_auto_20191007_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoriaPadre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TpPythonApp.Categoria'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='categorias',
            field=models.ManyToManyField(to='TpPythonApp.Categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TpPythonApp.Categoria'),
        ),
    ]
