# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-07 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TpPythonApp', '0005_auto_20191007_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='TpPythonApp.Producto'),
        ),
    ]
