# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-16 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TpPythonApp', '0008_auto_20191007_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(default='sinNombre', max_length=255),
        ),
    ]
