# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-08 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TpPythonApp', '0011_auto_20191016_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='', max_length=255),
        ),
    ]
