# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-09 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TpPythonApp', '0014_auto_20191109_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='TpPythonApp.Producto'),
        ),
    ]
