# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-09 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TpPythonApp', '0015_auto_20191109_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precio',
            name='producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Precio',
        ),
    ]
